/*!
 * Copyright (c) 2024 PLANKA Software GmbH
 * Licensed under the Fair Use License: https://github.com/plankanban/planka/blob/master/LICENSE.md
 */

export default [
  'berry-red',
  'pumpkin-orange',
  'lagoon-blue',
  'pink-tulip',
  'light-mud',
  'orange-peel',
  'bright-moss',
  'antique-blue',
  'dark-granite',
  'turquoise-sea',
  // Novas cores inspiradas em Hogwarts e brasões
  'gryffindor-red',
  'slytherin-green',
  'hufflepuff-gold',
  'ravenclaw-blue',
  'hogwarts-purple',
  'golden-snitch',
  'magical-silver',
  'dark-wizard',
  'phoenix-orange',
  'unicorn-white',
  'deep-teal',
  'bright-coral',
  'dusty-rose',
  'slate-gray',
  'soft-pink',
  'lavender',
  'powder-blue',
  'mint-green',
  'peach',
  'lilac',
  'cornflower-blue',
  'pale-dogwood',
  'ocean-breeze',
  'pink-purple-dream',
  'galaxy-dream',
  'vibrant-sunset',
  'pastel-dream',
  'moonlit-asteroid',
  'cool-sky',
  'emerald-water',
  'purple-dusk',
  'deep-space',
  'ocean-depths',
  'dark-wine',
];
