name: Build Docker Image Manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (leave empty for package.json version)'
        required: false
        type: string
      platform:
        description: 'Platform to build'
        required: false
        default: 'linux/amd64'
        type: choice
        options:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7

jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from package.json
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ github.event.inputs.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show image info
        run: |
          echo "✅ Docker image built and pushed successfully!"
          echo "Image: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}"
          echo "Latest: ghcr.io/${{ github.repository }}:latest"
          echo "Platform: ${{ github.event.inputs.platform }}"
